# Generated by Django 5.2.12 on 2026-06-19 06:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_submission_professional'),
        ('paid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_code', models.CharField(max_length=32, unique=True)),
                ('doctor_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('patient_whatsapp', models.CharField(blank=True, max_length=32)),
                ('patient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('form_family', models.CharField(choices=[('LEGACY', 'Legacy behavioral'), ('PAID', 'Paid assessment'), ('SELF', 'Self screening')], max_length=16)),
                ('form_code', models.CharField(blank=True, max_length=64)),
                ('form_title', models.CharField(blank=True, max_length=255)),
                ('form_version', models.CharField(blank=True, max_length=64)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('amount_paise', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_status', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('SKIPPED', 'Skipped'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='NOT_REQUIRED', max_length=32)),
                ('current_status', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('OPENED', 'Opened'), ('PAYMENT_PENDING', 'Payment pending'), ('PAYMENT_COMPLETED', 'Payment completed'), ('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted'), ('REPORT_PENDING', 'Report pending'), ('REPORT_PROCESSING', 'Report processing'), ('REPORT_GENERATED', 'Report generated'), ('REPORT_SENT', 'Report sent'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=32)),
                ('completion_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completed_questions', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('access_token_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('created_by_user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('in_progress_at', models.DateTimeField(blank=True, null=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('report_generated_at', models.DateTimeField(blank=True, null=True)),
                ('report_sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_stage', models.CharField(blank=True, max_length=64)),
                ('failure_reason', models.TextField(blank=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='content.registeredprofessional')),
                ('legacy_submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_case', to='content.submission')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_case', to='paid.espayorder')),
                ('paid_submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_case', to='paid.essubsubmission')),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_case', to='paid.esrepreport')),
            ],
            options={
                'db_table': 'workflow_cases',
            },
        ),
        migrations.CreateModel(
            name='WorkflowDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('APP', 'App'), ('SYSTEM', 'System')], max_length=16)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('OPENED', 'Opened'), ('FAILED', 'Failed'), ('SIMULATED', 'Simulated')], default='QUEUED', max_length=16)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='paid.workflowcase')),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paid.espayemaillog')),
            ],
            options={
                'db_table': 'workflow_delivery_attempts',
            },
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('stage', models.CharField(blank=True, max_length=64)),
                ('status_from', models.CharField(blank=True, max_length=32)),
                ('status_to', models.CharField(blank=True, max_length=32)),
                ('actor_type', models.CharField(choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('SYSTEM', 'System'), ('GATEWAY', 'Gateway'), ('ADMIN', 'Admin')], default='SYSTEM', max_length=16)),
                ('actor_identifier', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='paid.workflowcase')),
            ],
            options={
                'db_table': 'workflow_events',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_required', models.BooleanField(default=False)),
                ('amount_paise', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('gateway', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('SKIPPED', 'Skipped')], default='NOT_REQUIRED', max_length=32)),
                ('reference_id', models.CharField(blank=True, max_length=128)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True)),
                ('raw_payload_json', models.JSONField(blank=True, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='paid.workflowcase')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paid.espayorder')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paid.espaytransaction')),
            ],
            options={
                'db_table': 'workflow_payments',
            },
        ),
        migrations.CreateModel(
            name='WorkflowReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=32)),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_doctor_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_patient_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_delivery_status', models.CharField(blank=True, max_length=32)),
                ('patient_delivery_status', models.CharField(blank=True, max_length=32)),
                ('error_text', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_tracking', to='paid.workflowcase')),
                ('legacy_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.submission')),
                ('paid_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paid.essubsubmission')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paid.esrepreport')),
            ],
            options={
                'db_table': 'workflow_reports',
            },
        ),
        migrations.AddIndex(
            model_name='workflowcase',
            index=models.Index(fields=['doctor', 'current_status'], name='workflow_ca_doctor__e68dca_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowcase',
            index=models.Index(fields=['form_family', 'current_status'], name='workflow_ca_form_fa_0c6c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowcase',
            index=models.Index(fields=['payment_status'], name='workflow_ca_payment_f95a05_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowcase',
            index=models.Index(fields=['created_at'], name='workflow_ca_created_ba6786_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdeliveryattempt',
            index=models.Index(fields=['case', 'channel'], name='workflow_de_case_id_2428dd_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdeliveryattempt',
            index=models.Index(fields=['status'], name='workflow_de_status_53f785_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdeliveryattempt',
            index=models.Index(fields=['created_at'], name='workflow_de_created_49ebe1_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowevent',
            index=models.Index(fields=['case', 'occurred_at'], name='workflow_ev_case_id_6f8739_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowevent',
            index=models.Index(fields=['event_type'], name='workflow_ev_event_t_e83845_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowevent',
            index=models.Index(fields=['stage'], name='workflow_ev_stage_972095_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowpayment',
            index=models.Index(fields=['status'], name='workflow_pa_status_127554_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowpayment',
            index=models.Index(fields=['gateway'], name='workflow_pa_gateway_260d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowreport',
            index=models.Index(fields=['status'], name='workflow_re_status_d344a2_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowreport',
            index=models.Index(fields=['generated_at'], name='workflow_re_generat_d71c29_idx'),
        ),
    ]
